services:
  nest-dev:
    container_name: viacao_sete_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
      - '9229:9229'
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: viacao_sete_postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: viacao_sete_redis
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: >
      sh -c "redis-server --requirepass \"$REDIS_PASSWORD\""

  nest-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  pgdata:
