export const ATTACHMENT_REPOSITORY = Symbol('ATTACHMENT_REPOSITORY');
export const CREATE_ATTACHMENT_SERVICE = Symbol('CREATE_ATTACHMENT_SERVICE');
export const FIND_ATTACHMENTS_BY_ENTITY_ID_SERVICE = Symbol(
  'FIND_ATTACHMENTS_BY_ENTITY_ID_SERVICE',
);
