export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const TRANSACTION_CATEGORY_REPOSITORY = Symbol(
  'TRANSACTION_CATEGORY_REPOSITORY',
);

export const CREATE_TRANSACTION_SERVICE = Symbol('CREATE_TRANSACTION_SERVICE');
export const CREATE_TRANSACTION_CATEGORY_SERVICE = Symbol(
  'CREATE_TRANSACTION_CATEGORY_SERVICE',
);
export const LIST_TRANSACTIONS_SERVICE = Symbol('LIST_TRANSACTIONS_SERVICE');
