export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const TRANSACTION_CATEGORY_REPOSITORY = Symbol(
  'TRANSACTION_CATEGORY_REPOSITORY',
);
export const PAYMENT_METHOD_REPOSITORY = Symbol('PAYMENT_METHOD_REPOSITORY');

export const CREATE_TRANSACTION_SERVICE = Symbol('CREATE_TRANSACTION_SERVICE');
export const UPDATE_TRANSACTION_SERVICE = Symbol('UPDATE_TRANSACTION_SERVICE');
export const DELETE_TRANSACTION_SERVICE = Symbol('DELETE_TRANSACTION_SERVICE');
export const CREATE_TRANSACTION_CATEGORY_SERVICE = Symbol(
  'CREATE_TRANSACTION_CATEGORY_SERVICE',
);
export const UPDATE_TRANSACTION_CATEGORY_SERVICE = Symbol(
  'UPDATE_TRANSACTION_CATEGORY_SERVICE',
);
export const DELETE_TRANSACTION_CATEGORY_SERVICE = Symbol(
  'DELETE_TRANSACTION_CATEGORY_SERVICE',
);
export const LIST_TRANSACTIONS_SERVICE = Symbol('LIST_TRANSACTIONS_SERVICE');
export const LIST_TRANSACTION_CATEGORIES_SERVICE = Symbol(
  'LIST_TRANSACTION_CATEGORIES_SERVICE',
);
export const EXTRACT_TRANSACTION_SUMMARY_SERVICE = Symbol(
  'EXTRACT_TRANSACTION_SUMMARY_SERVICE',
);
export const CREATE_PAYMENT_METHOD_SERVICE = Symbol(
  'CREATE_PAYMENT_METHOD_SERVICE',
);
export const DELETE_PAYMENT_METHOD_SERVICE = Symbol(
  'DELETE_PAYMENT_METHOD_SERVICE',
);
export const LIST_PAYMENT_METHODS_SERVICE = Symbol(
  'LIST_PAYMENT_METHODS_SERVICE',
);
