export const TRANSACTION_REPOSITORY = Symbol('TRANSACTION_REPOSITORY');
export const TRANSACTION_CATEGORY_REPOSITORY = Symbol(
  'TRANSACTION_CATEGORY_REPOSITORY',
);
export const TRANSACTION_LINE_DETAILS_REPOSITORY = Symbol(
  'TRANSACTION_LINE_DETAILS_REPOSITORY',
);

export const CREATE_TRANSACTION_SERVICE = Symbol('CREATE_TRANSACTION_SERVICE');
export const CREATE_TRANSACTION_CATEGORY_SERVICE = Symbol(
  'CREATE_TRANSACTION_CATEGORY_SERVICE',
);
export const LIST_TRANSACTIONS_SERVICE = Symbol('LIST_TRANSACTIONS_SERVICE');
export const LIST_TRANSACTION_CATEGORIES_SERVICE = Symbol(
  'LIST_TRANSACTION_CATEGORIES_SERVICE',
);
export const EXTRACT_TRANSACTION_SUMMARY_SERVICE = Symbol(
  'EXTRACT_TRANSACTION_SUMMARY_SERVICE',
);
